services:
  web:
    container_name: notes_management_web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
